FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:20

# Instalar utilidades adicionales
RUN apt-get update && apt-get install -y \
    default-mysql-client \
    && rm -rf /var/lib/apt/lists/*
